image: node:latest

stages:
    - build
    - test_development

build:
    stage: build
    script:
        - npm install --save

test_development:
    stage: test_development
    script:
        - npm run gitlab:test